endpoints:
  health:
    enabled: true
micronaut:
  server:
    cors:
      enabled: true
  application:
    name: productAPI
cassandra:
  default:
    basic:
      contact-points:
        - 192.168.100.2:9042
      session-keyspace: product
      load-balancing-policy:
        local-datacenter: datacenter1